### ISSUE TITLE
Perform a release

### ISSUE THREAD

**Issue by josephtaylor** [silvermine/videojs-airplay#27]
There's been several commits to this repo since the 1.0.0 release in April 2018.

Why hasn't a release been published to npm?

**Comment by jthomerson** [comment]
Hey @josephtaylor, jumping on an FOSS project for not doing something you think they should have done in the free software they provide you is not cool.

Yeah, there's been some commits - 16 to be exact - but almost all of them were for build-related things. The only thing I see that could possibly impact someone is the fix for #11 and #14. If you needed one of those, it'd be much better to say "thanks for the work on this plugin. I need the fix for X. Would it be possible to cut a release?"

Nonetheless, I just published 1.0.1.
