### ISSUE TITLE
AirPlay fails for FairPlay protected content

### ISSUE THREAD

**Issue by cfra** [silvermine/videojs-airplay#42]
While videojs-airplay works fine for unprotected content - great work on that - it fails for me when I am trying to send FairPlay protected content that is being played back by videojs-contrib-eme.

In this case, audio starts playing back on the AppleTV I am sending to, but video is still being shown only on the source device.

Not sure whose responsibility this is as the documentation on the inner workings of AirPlay is quite sparse.

**Comment by yokuze** [comment]
Hi @cfra. This plugin is basically a simple button that [calls the browser's native `webkitShowPlaybackTargetPicker` method](https://github.com/silvermine/videojs-airplay/blob/master/src/js/enableAirPlay.js#L52) to open the AirPlay menu. The rest of the AirPlay process is handled natively by the browser and target device, so it's very unlikely the issue you're seeing is caused by `@silvermine/videojs-airplay`.

> documentation on the inner workings of AirPlay is quite sparse.

I agree with you there!

If you find that the issue is somehow caused by this plugin and you can provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates it, feel free to comment here and we'll reopen the issue. Thanks.

**Comment by cfra** [comment]
I found the reason by now: Using AirPlay requires the usage of Safari's native HLS streaming implementation. If `overrideNative` is set to `true`, it will fail in weird ways.
