### ISSUE TITLE
package not found on npm

### ISSUE THREAD

**Issue by rechl** [silvermine/videojs-airplay#9]
```
 npm install silvermine-videojs-airplay --save
npm ERR! code E404
npm ERR! 404 Not Found: silvermine-videojs-airplay@latest
```

Is it still available?

**Comment by jthomerson** [comment]
Sorry about that! We'd been using the plugin by referencing it via commit hash and forgot to release it to NPM. I just pushed version 1.0.0. **NOTE:** We also renamed the package to `@silvermine/videojs-airplay` since we're trying to migrate all of our packages to an NPM organization. See the [README](https://github.com/silvermine/videojs-airplay#readme) for updated information.

**Comment by rechl** [comment]
thank you!
